### ISSUE TITLE
Request for a pre-made code template for using Redux Toolkit with Vite in a React application

### ISSUE THREAD

**Issue by umeh-promise** [brillout/awesome-redux#12]
Is it possible to have a pre-made code template for using Redux Toolkit with Vite in a React application? I am looking for a starting point to integrate Redux Toolkit and Vite without having to manually configure the project setup. It would be helpful to have a boilerplate code that includes all the necessary dependencies, files, and configurations for a smooth integration.

Specifically, I want to use Redux Toolkit, which is a recommended way to manage state in a React application, and Vite, which is a build tool that offers fast development experience by optimizing build times. However, setting up the project from scratch can be time-consuming, and I would like to save time by using a boilerplate code that I can customize to fit my needs.
Thank you.

**Comment by brillout** [comment]
https://vite-plugin-ssr.com/migration/v1-design#why-the-v1-design
